name: Combine Case JSON Files

on:
  push:
    paths:
      - "cases/**/case.json"

jobs:
  combine-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          npm install

      - name: Combine JSON files
        run: node combine-cases.js

      - name: Commit and push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(cases): Update combined cases.json"
          file_pattern: cases.json
